<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tamara Mallory">
<meta name="dcterms.date" content="2025-04-03">

<title>Mandatory school attendance program</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="TamaraMallory_problem-set-6_files/libs/clipboard/clipboard.min.js"></script>
<script src="TamaraMallory_problem-set-6_files/libs/quarto-html/quarto.js"></script>
<script src="TamaraMallory_problem-set-6_files/libs/quarto-html/popper.min.js"></script>
<script src="TamaraMallory_problem-set-6_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="TamaraMallory_problem-set-6_files/libs/quarto-html/anchor.min.js"></script>
<link href="TamaraMallory_problem-set-6_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="TamaraMallory_problem-set-6_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="TamaraMallory_problem-set-6_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="TamaraMallory_problem-set-6_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="TamaraMallory_problem-set-6_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#step-1-determine-if-process-of-assigning-treatment-is-rule-based" id="toc-step-1-determine-if-process-of-assigning-treatment-is-rule-based" class="nav-link active" data-scroll-target="#step-1-determine-if-process-of-assigning-treatment-is-rule-based">Step 1: Determine if process of assigning treatment is rule-based</a></li>
  <li><a href="#step-2-determine-if-the-design-is-fuzzy-or-sharp" id="toc-step-2-determine-if-the-design-is-fuzzy-or-sharp" class="nav-link" data-scroll-target="#step-2-determine-if-the-design-is-fuzzy-or-sharp">Step 2: Determine if the design is fuzzy or sharp</a></li>
  <li><a href="#step-3-check-for-discontinuity-in-running-variable-around-cutpoint" id="toc-step-3-check-for-discontinuity-in-running-variable-around-cutpoint" class="nav-link" data-scroll-target="#step-3-check-for-discontinuity-in-running-variable-around-cutpoint">Step 3: Check for discontinuity in running variable around cutpoint</a></li>
  <li><a href="#step-4-check-for-discontinuity-in-outcome-across-running-variable" id="toc-step-4-check-for-discontinuity-in-outcome-across-running-variable" class="nav-link" data-scroll-target="#step-4-check-for-discontinuity-in-outcome-across-running-variable">Step 4: Check for discontinuity in outcome across running variable</a></li>
  <li><a href="#step-5-measure-the-size-of-the-effect" id="toc-step-5-measure-the-size-of-the-effect" class="nav-link" data-scroll-target="#step-5-measure-the-size-of-the-effect">Step 5: Measure the size of the effect</a>
  <ul class="collapse">
  <li><a href="#parametric-estimation" id="toc-parametric-estimation" class="nav-link" data-scroll-target="#parametric-estimation">Parametric estimation</a></li>
  <li><a href="#nonparametric-estimation" id="toc-nonparametric-estimation" class="nav-link" data-scroll-target="#nonparametric-estimation">Nonparametric estimation</a></li>
  <li><a href="#nonparametric-sensitivity-checks" id="toc-nonparametric-sensitivity-checks" class="nav-link" data-scroll-target="#nonparametric-sensitivity-checks">Nonparametric sensitivity checks</a></li>
  </ul></li>
  <li><a href="#step-6-compare-all-the-effects" id="toc-step-6-compare-all-the-effects" class="nav-link" data-scroll-target="#step-6-compare-all-the-effects">Step 6: Compare all the effects</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="TamaraMallory_problem-set-6.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mandatory school attendance program</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tamara Mallory </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 3, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<hr>
<p>There is substantial research and evidence that <a href="http://graphics8.nytimes.com/packages/pdf/nyregion/20110617attendancereport.pdf">class attendance has a positive and significant effect on student performance</a>. Because of this, state and local government agencies and school districts have designed programs and policies that incentivize students to not miss school days. Examples include tangible prizes like <a href="https://www.nytimes.com/2011/06/17/nyregion/city-reduces-chronic-absenteeism-in-public-schools.html">colorful pendants and free tickets to events</a>, <a href="https://cityroom.blogs.nytimes.com/2011/02/10/schools-use-celebrity-robo-calls-to-battle-truancy/">automated calls from celebrities</a>, or <a href="https://people.ucsc.edu/~cdobkin/Papers/2010%20Skipping%20class%20in%20college%20and%20exam%20performance%20Evidence%20from%20a%20regression%20discontinuity%20classroom%20experiment.pdf">class policies that mandate attendance</a>.</p>
<p>Existing research has used a range of methods to test the relationship between attendance programs and student performance, including <a href="https://dx.doi.org/10.1016/j.sbspro.2016.07.051">simple regression analysis</a>, <a href="https://dx.doi.org/10.3200/JECE.39.3.213-227">randomized experiments</a>, and <a href="https://people.ucsc.edu/~cdobkin/Papers/2010%20Skipping%20class%20in%20college%20and%20exam%20performance%20Evidence%20from%20a%20regression%20discontinuity%20classroom%20experiment.pdf">regression discontinuity approaches</a>.</p>
<p>In this assignment, you will use regression discontinuity approaches to measure the effect of a hypothetical program on hypothetical student grades (this data is 100% fake).</p>
<p>In this simulated program, high school students who have less than 80% attendance during their junior year (11th grade) are assigned to a mandatory school attendance program during their senior year (12th grade). This program requires them to attend school and also provides them with additional support and tutoring to help them attend and remain in school. At the end of their senior year, students take a final test to assess their overall learning in high school.</p>
<p>The dataset I’ve provided contains four columns:</p>
<ul>
<li><code>id</code>: A randomly assigned student ID number</li>
<li><code>attendance</code>: The proportion of days of school attended during a student’s junior year (ranges from 0 to 100)</li>
<li><code>treatment</code>: Binary variable indicating if a student was assigned to the attendance program during their senior year</li>
<li><code>grade</code>: A student’s final test grade at the end of their senior year</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rdrobust)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rddensity)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># This turns off this message that appears whenever you use summarize():</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># `summarise()` ungrouping output (override with `.groups` argument)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">dplyr.summarise.inform =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>program <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"C:/Users/marap/OneDrive/Portfolio/Portfolio Projects/data/attendance_program.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="step-1-determine-if-process-of-assigning-treatment-is-rule-based" class="level1">
<h1>Step 1: Determine if process of assigning treatment is rule-based</h1>
<p><strong>Was assignment to this program based on an arbitrary rule? Is it a good candidate for a regression discontinuity approach? Why or why not?</strong> The assignment to this program was based on an arbitrary rule. The individuals chosen were chosen by attendance which is naturally occurring with the cut off value.The individuals were put in the treatment and control groups based on the cut off value. It is a good candidate for regression discontinuity approach because the assignment of the treatment and control groups were not randomly assigned.</p>
</section>
<section id="step-2-determine-if-the-design-is-fuzzy-or-sharp" class="level1">
<h1>Step 2: Determine if the design is fuzzy or sharp</h1>
<p>Make a plot that shows the running variable (<code>attendance</code>) on the x-axis and the program indicator variable (<code>treatment</code>) on the y-axis. Show the relationship using points (<code>geom_point</code>) and color the points by <code>treatment</code>.</p>
<p><strong>How strict was the application of the rule? Did any students with attendance above 80% get into the attendance program, or did any students with attendance under 80% not get into the program? Is there a sharp difference in treatment at the cutpoint?</strong> The application of the rule was applied very strict. The graph did not show any student with attendance above 80% get into the attendance program nor did ant student with attendance under 80% not get into the program. There is a sharp difference in the treatment at the cut point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dot plot with attendance on the x-axis and treatment on the y-axis</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(program, <span class="fu">aes</span>(<span class="at">x =</span> attendance, <span class="at">y =</span> treatment, <span class="at">color =</span> treatment)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Make points small and semi-transparent since there are lots of them</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="dv">0</span>, <span class="at">height =</span> <span class="fl">0.25</span>, <span class="at">seed =</span> <span class="dv">1234</span>)) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add vertical line</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">80</span>) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add labels</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Attendance in junior year"</span>, <span class="at">y =</span> <span class="st">"Participated in attendance program"</span>) <span class="sc">+</span> </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Turn off the color legend, since it's redundant</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TamaraMallory_problem-set-6_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-3-check-for-discontinuity-in-running-variable-around-cutpoint" class="level1">
<h1>Step 3: Check for discontinuity in running variable around cutpoint</h1>
<p>Next, you should check that there was no manipulation in the running variable. We don’t want to see a ton of students with 81% or 79% attendance, since that could be a sign that administrators fudged the numbers to either push students into the program or out of the program.</p>
<p>First, make a histogram of the running variable and see if there are any big jumps around the threshold. Fill the histogram by <code>treatment</code> and add a vertical line at 80 (<code>geom_vline(xintercept = 80)</code>) to show the cutoff. Use an approprite bin width. If the column near 80 is split into two different colors (it might be, since it might be showing 79 and 80 together), add <code>boundary = 80</code> inside <code>geom_histogram()</code> to force ggplot to start a bar at 80 and not include 79.</p>
<p><strong>Does it look like there’s an unexpected jump in the running variable around the cutoff?</strong> At the 78-79 range there is a dip in attendance, which might signal that people are potentially falsely reporting slightly higher attendance to get out of the program.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of attendance</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(program, <span class="fu">aes</span>(<span class="at">x =</span> attendance, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">fill =</span> treatment)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"white"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">boundary =</span> <span class="dv">80</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">80</span>) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Attendance in junior year"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TamaraMallory_problem-set-6_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Next, conduct a McCrary density test with <code>rdplotdensity()</code> from the <code>rddensity</code> library. Refer to the in-class example for the syntax (you’ll need to specify <code>rdd</code>, <code>X</code> (note that it’s capitalized), and <code>type = "both"</code>). Also, if you don’t want two plots to show up when you render, make sure you assign the output of <code>rdplotdensity()</code> to a variable.</p>
<p><strong>Is there a substantial jump at the cutpoint?</strong> There is a not substantial jump at the cutpoint. The p-value for the size of that overlap is 0.4384 which is a lot larger than 0.05, so we can’t say for certain that there’s a significant difference between the two lines.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># McCrary test</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>test_density <span class="ot">&lt;-</span> <span class="fu">rddensity</span>(program<span class="sc">$</span>attendance, <span class="at">c =</span> <span class="dv">80</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(test_density)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Manipulation testing using local polynomial density estimation.

Number of obs =       1200
Model =               unrestricted
Kernel =              triangular
BW method =           estimated
VCE method =          jackknife

c = 80                Left of c           Right of c          
Number of obs         681                 519                 
Eff. Number of obs    384                 421                 
Order est. (p)        2                   2                   
Order bias (q)        3                   3                   
BW est. (h)           13.574              12.521              

Method                T                   P &gt; |T|             
Robust                0.7748              0.4384              </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in summary.CJMrddensity(test_density): There are repeated observations.
Point estimates and standard errors have been adjusted. Use option
massPoints=FALSE to suppress this feature.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
P-values of binomial tests (H0: p=0.5).

Window Length / 2          &lt;c     &gt;=c    P&gt;|T|
0.820                      20      28    0.3123
1.640                      50      63    0.2589
2.460                      72      90    0.1815
3.280                     102     110    0.6308
4.100                     126     146    0.2493
4.920                     149     172    0.2194
5.740                     175     205    0.1367
6.560                     198     232    0.1114
7.380                     229     254    0.2748
8.200                     258     280    0.3653</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>plot_density_test <span class="ot">&lt;-</span> <span class="fu">rdplotdensity</span>(<span class="at">rdd =</span> test_density,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">X =</span> program<span class="sc">$</span>attendance,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">type =</span> <span class="st">"both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TamaraMallory_problem-set-6_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-4-check-for-discontinuity-in-outcome-across-running-variable" class="level1">
<h1>Step 4: Check for discontinuity in outcome across running variable</h1>
<p>Make a scatterplot with the running variable on the x-axis (<code>attendance</code>) and the outcome variable on the y-axis (<code>grade</code>), with the points colored by treatment (<code>treatment</code>). Make the points small (<code>size = 0.5</code> or something similar) and semitransparent (<code>alpha = 0.5</code> or something similar) since there are a lot of them. Add a vertical line at the cutoff point. Add two <code>geom_smooth()</code> lines: one using data before the cutoff and one using data after the cutoff. Make sure both lines use <code>method = "lm"</code>. Refer to the example for the code you need to do this.</p>
<p><strong>Based on this graph, does the program have an effect? Is there a discontinuity in outcome around the cutpoint? Interpret the effect (or non-effect) of the program.</strong> Based on the graph the program does have an effect. There is not discontinuity in the outcome around the cutpoint.it looks like there might be a jump at the cutoff, but it seems small. People with 79% attendance have much higher average grades than those with 81%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graph showing discontinuity in grades across levels of attendance</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(program, <span class="fu">aes</span>(<span class="at">x =</span> attendance, <span class="at">y =</span> grade, </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">color =</span> treatment)) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add a line based on a linear model for the people attendance percentage 80 or less</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> <span class="fu">filter</span>(program, grade <span class="sc">&lt;=</span> <span class="dv">80</span>),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add a line based on a linear model for the people attendance greater than 80</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> <span class="fu">filter</span>(program, attendance <span class="sc">&gt;</span> <span class="dv">80</span>), </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">80</span>) <span class="sc">+</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Attendance in junior year"</span>, <span class="at">y =</span> <span class="st">"Grade at end of high school"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TamaraMallory_problem-set-6_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-5-measure-the-size-of-the-effect" class="level1">
<h1>Step 5: Measure the size of the effect</h1>
<p>Now you need to measure the size and statistical significance of the discontinuity. If there’s a jump because of the program, how big is it and how much can we trust it? You’ll do this two ways: (1) parametrically with linear regression and (2) nonparametrically with curvy lines and fancy econometrics algorithms built in to the <code>rdrobust()</code> function.</p>
<section id="parametric-estimation" class="level2">
<h2 class="anchored" data-anchor-id="parametric-estimation">Parametric estimation</h2>
<p>Create a new dataset based on <code>program</code> that has a new variable in it named <code>attendance_centered</code>. This will be the value of <code>attendance</code> minus 80. This centers student attendance around the cutpoint (if a student had 85% attendance, they’d have a value of 5; if they had 70% attendance, they’d have a value of 10; etc.) and makes it easier to interpret the intercept coefficient in linear models since it shifts the y-intercept up to the cutpoint instead of zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add column to program that centers attendance</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>attendance_centered <span class="ot">&lt;-</span> program <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">attendance_centered =</span> attendance <span class="sc">-</span> <span class="dv">80</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Run a regression model explaining <code>grade</code> with <code>attendance_centered + treatment</code>:</p>
<p><span class="math display">\[
\text{Grade} = \beta_0 + \beta_1 \text{Attendance (centered)} + \beta_2 \text{Program} + \epsilon
\]</span></p>
<p>Make sure you use the data frame that has your new <code>attendance_centered</code> variable.</p>
<p><strong>Interpret the three coefficients. How big is the effect of the program? Is it statistically significant?</strong> Because we centered test scores, it shows the average final score at the 80% threshold. People who had attendance right at threshold scored 66.2 points on average on the final test. The coefficient for attendance_centered. For every percentage point above 80 that people attend school, they score 1.56 points higher on the final test. Being in the attendance program increases final scores by 5.88 points. This difference is statistically significant (t = 9.89; p &lt; 0.001).**</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear model</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>model_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> attendance_centered <span class="sc">+</span> treatment,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> attendance_centered)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_simple)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term                estimate std.error statistic  p.value
  &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)            66.2     0.330     201.   0       
2 attendance_centered     1.56    0.0203     76.6  0       
3 treatmentTRUE           5.88    0.595       9.89 3.07e-22</code></pre>
</div>
</div>
<p>Now make two new datasets based on the one you made previously with the <code>attendance_centered</code> variable. Filter one so that it only contains observations where <code>attendance_centered</code> is between -5 and 5, and filter the other so that it only contains observations where <code>attendance_centered</code> is between -10 and 10.</p>
<p>Run the same model (<code>grade ~ attendance_centered + program</code>) using each of these data frames. Interpret the coefficients. Are they different from the model that uses the complete data?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data and model with bandwidth = 5</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>program_bw_5 <span class="ot">&lt;-</span> attendance_centered <span class="sc">|&gt;</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(attendance_centered <span class="sc">&gt;=</span> <span class="sc">-</span><span class="dv">5</span>, attendance_centered <span class="sc">&lt;=</span> <span class="dv">5</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>model_bw_5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> attendance_centered <span class="sc">+</span> treatment,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> <span class="fu">filter</span>(attendance_centered,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                                attendance_centered <span class="sc">&gt;=</span> <span class="sc">-</span><span class="dv">5</span> <span class="sc">&amp;</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>                                  attendance_centered <span class="sc">&lt;=</span> <span class="dv">5</span>))</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_bw_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term                estimate std.error statistic   p.value
  &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)            64.0      0.859     74.6  2.68e-207
2 attendance_centered     2.15     0.272      7.91 4.07e- 14
3 treatmentTRUE          12.3      1.57       7.84 6.62e- 14</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data and model with bandwidth = 10</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>program_bw_10 <span class="ot">&lt;-</span> attendance_centered <span class="sc">|&gt;</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(attendance_centered <span class="sc">&gt;=</span> <span class="sc">-</span><span class="dv">10</span> <span class="sc">&amp;</span> attendance_centered <span class="sc">&lt;=</span> <span class="dv">10</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>model_bw_10 <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> attendance_centered <span class="sc">+</span> treatment,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> <span class="fu">filter</span>(attendance_centered,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                                attendance_centered <span class="sc">&gt;=</span> <span class="sc">-</span><span class="dv">10</span> <span class="sc">&amp;</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>                                  attendance_centered <span class="sc">&lt;=</span> <span class="dv">10</span>))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_bw_10)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term                estimate std.error statistic  p.value
  &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)            64.2     0.601      107.  0       
2 attendance_centered     2.03    0.0967      21.0 1.53e-74
3 treatmentTRUE          11.9     1.09        10.9 2.69e-25</code></pre>
</div>
</div>
<p><strong>Put all three models in a side-by-side table with <code>modelsummary()</code>. How does the coefficient for <code>program</code> change across the model specifications? How does the number of observations change? What advantages and disadvantages are there to restricting the data to ±5 or ±10 around the cutpoint? Which program effect do you believe the most? Why?</strong> The size of the jump at the cutoff changes as the bandwidth shrinks. If we only look at observations that are ±10 percent around the cutoff, the gap grows a lot to 11.87, which is significant (p &lt; 0.001). Narrowing the bandwidth more to ±5 gives us a gap of 12.34 (still significant; p &lt; 0.001). The coefficients change slightly decrease across the models. With narrower bandwidths the observations drop. The advantages of a bandwidth of ±10 is that it has more observations and the data can be used to generalize. The con is that the schools looked at might be too different than the treatment group. The advantage of a bandwidth of ±5 is that it focuses on comparable schools. The con is that it has a significantly smaller sample size. I believe the ±10 the most since the results can be more generalized and that is the goal of programs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># All three models</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(<span class="fu">list</span>(<span class="st">"Full data"</span> <span class="ot">=</span> model_simple,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Bandwidth = 10"</span> <span class="ot">=</span> model_bw_10,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Bandwidth = 5"</span> <span class="ot">=</span> model_bw_5))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<!-- preamble start -->

    <script>

      function styleCell_n1ru88w61d08yqtmbr0t(i, j, css_id) {
          var table = document.getElementById("tinytable_n1ru88w61d08yqtmbr0t");
          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors
          if (cell) {
              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);
              cell.classList.add(css_id);
          } else {
              console.warn(`Cell at (${i}, ${j}) not found.`);
          }
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_n1ru88w61d08yqtmbr0t');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_n1ru88w61d08yqtmbr0t(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_n1ru88w61d08yqtmbr0t");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: 14, j: 1 }, { i: 14, j: 2 }, { i: 14, j: 3 },  ], css_id: 'tinytable_css_yaeohe8s51959u4uhzve',}, 
          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 10, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 11, j: 0 }, { i: 12, j: 0 }, { i: 13, j: 0 },  ], css_id: 'tinytable_css_pcxtlsi6wt7uerf87u4b',}, 
          { positions: [ { i: 6, j: 0 },  ], css_id: 'tinytable_css_otvx9bde6g7viyfd59lb',}, 
          { positions: [ { i: 6, j: 1 }, { i: 6, j: 3 }, { i: 6, j: 2 },  ], css_id: 'tinytable_css_hck4h3vtrwyyzr6pqcjp',}, 
          { positions: [ { i: 1, j: 1 }, { i: 3, j: 1 }, { i: 5, j: 1 }, { i: 4, j: 2 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 }, { i: 12, j: 1 }, { i: 13, j: 1 }, { i: 12, j: 2 }, { i: 2, j: 1 }, { i: 1, j: 2 }, { i: 4, j: 1 }, { i: 3, j: 2 }, { i: 2, j: 3 }, { i: 5, j: 2 }, { i: 4, j: 3 }, { i: 7, j: 2 }, { i: 8, j: 2 }, { i: 9, j: 2 }, { i: 10, j: 2 }, { i: 11, j: 2 }, { i: 10, j: 3 }, { i: 13, j: 2 }, { i: 12, j: 3 }, { i: 2, j: 2 }, { i: 1, j: 3 }, { i: 3, j: 3 }, { i: 8, j: 3 }, { i: 5, j: 3 }, { i: 7, j: 3 }, { i: 9, j: 3 }, { i: 11, j: 3 }, { i: 13, j: 3 },  ], css_id: 'tinytable_css_asw9c982yhps4o4z224b',}, 
          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_ariifx7eng2spyh45an9',}, 
          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 }, { i: 0, j: 3 },  ], css_id: 'tinytable_css_8gyzz7728xxg8btcz602',}, 
          { positions: [ { i: 14, j: 0 },  ], css_id: 'tinytable_css_112s2v9gwb7sr61sv4vj',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  styleCell_n1ru88w61d08yqtmbr0t(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <style>
      /* tinytable css entries after */
      .table td.tinytable_css_yaeohe8s51959u4uhzve, .table th.tinytable_css_yaeohe8s51959u4uhzve { text-align: center; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_pcxtlsi6wt7uerf87u4b, .table th.tinytable_css_pcxtlsi6wt7uerf87u4b { text-align: left; }
      .table td.tinytable_css_otvx9bde6g7viyfd59lb, .table th.tinytable_css_otvx9bde6g7viyfd59lb { text-align: left; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_hck4h3vtrwyyzr6pqcjp, .table th.tinytable_css_hck4h3vtrwyyzr6pqcjp { text-align: center; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_asw9c982yhps4o4z224b, .table th.tinytable_css_asw9c982yhps4o4z224b { text-align: center; }
      .table td.tinytable_css_ariifx7eng2spyh45an9, .table th.tinytable_css_ariifx7eng2spyh45an9 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_8gyzz7728xxg8btcz602, .table th.tinytable_css_8gyzz7728xxg8btcz602 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_112s2v9gwb7sr61sv4vj, .table th.tinytable_css_112s2v9gwb7sr61sv4vj { text-align: left; border-bottom: solid #d3d8dc 0.1em; }
    </style>
    <div class="container">
      <table class="table table-borderless" id="tinytable_n1ru88w61d08yqtmbr0t" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
        
              <tr>
                <th scope="col"> </th>
                <th scope="col">Full data</th>
                <th scope="col">Bandwidth = 10</th>
                <th scope="col">Bandwidth = 5</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td>(Intercept)</td>
                  <td>66.191</td>
                  <td>64.195</td>
                  <td>64.050</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.330)</td>
                  <td>(0.601)</td>
                  <td>(0.859)</td>
                </tr>
                <tr>
                  <td>attendance_centered</td>
                  <td>1.560</td>
                  <td>2.026</td>
                  <td>2.148</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.020)</td>
                  <td>(0.097)</td>
                  <td>(0.272)</td>
                </tr>
                <tr>
                  <td>treatmentTRUE</td>
                  <td>5.884</td>
                  <td>11.869</td>
                  <td>12.340</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.595)</td>
                  <td>(1.094)</td>
                  <td>(1.575)</td>
                </tr>
                <tr>
                  <td>Num.Obs.</td>
                  <td>1200</td>
                  <td>640</td>
                  <td>330</td>
                </tr>
                <tr>
                  <td>R2</td>
                  <td>0.907</td>
                  <td>0.505</td>
                  <td>0.169</td>
                </tr>
                <tr>
                  <td>R2 Adj.</td>
                  <td>0.907</td>
                  <td>0.503</td>
                  <td>0.163</td>
                </tr>
                <tr>
                  <td>AIC</td>
                  <td>7924.3</td>
                  <td>4297.8</td>
                  <td>2228.8</td>
                </tr>
                <tr>
                  <td>BIC</td>
                  <td>7944.6</td>
                  <td>4315.6</td>
                  <td>2244.0</td>
                </tr>
                <tr>
                  <td>Log.Lik.</td>
                  <td>-3958.135</td>
                  <td>-2144.889</td>
                  <td>-1110.378</td>
                </tr>
                <tr>
                  <td>F</td>
                  <td>5823.048</td>
                  <td>324.837</td>
                  <td>33.144</td>
                </tr>
                <tr>
                  <td>RMSE</td>
                  <td>6.55</td>
                  <td>6.91</td>
                  <td>7.00</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</section>
<section id="nonparametric-estimation" class="level2">
<h2 class="anchored" data-anchor-id="nonparametric-estimation">Nonparametric estimation</h2>
<p>Next you’ll use nonparametric estimation to figure out the size of the gap around the cutpoint. Remember from class that this means we’re not using straight lines anymore—we’re using curvy lines that don’t really have neat <span class="math inline">\(y = mx + b\)</span> equations behind them, so we can’t use <code>lm()</code> and regular coefficients. Instead, we can use <code>rdrobust</code> to measure the size of the gap.</p>
<p>Use <code>rdrobust</code> with all its default options to find the effect of the program. You’ll need to specify <code>y</code>, <code>x</code>, and <code>c</code>. Recall from the in-class example that you’ll need to type the name of the variables slighlty differently. To refer to the grade column in the program data frame, you’ll have to type <code>program$grade</code>. Also, make sure you pipe the output of <code>rdrobust()</code> to <code>summary()</code>, otherwise you won’t see the actual program effect (so make sure you type <code>rdrobust(...) |&gt; summary()</code>).</p>
<p><strong>How big of an effect does the program have at the cutpoint? Is the effect statistically significant?</strong> <strong>Important: if you see a negative number, you can pretend that it’s positive. It’s negative because the change in trend goes down.</strong> At the cutpoint there is 0.013 positive effect. The effect is not statistically signifcant. We cannot be certain that the effect is 0 because the p-value is 0.875.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rdrobust()</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: You don't need to use attendance_centered anymore; that was just for lm()</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rdrobust</span>(<span class="at">y =</span> program<span class="sc">$</span>grade, <span class="at">x =</span> program<span class="sc">$</span>attendance, <span class="at">c =</span> <span class="dv">80</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sharp RD estimates using local polynomial regression.

Number of Obs.                 1200
BW type                       mserd
Kernel                   Triangular
VCE method                       NN

Number of Obs.                  681          519
Eff. Number of Obs.             255          279
Order est. (p)                    1            1
Order bias  (q)                   2            2
BW est. (h)                   8.112        8.112
BW bias (b)                  12.449       12.449
rho (h/b)                     0.652        0.652
Unique Obs.                     627          451

=============================================================================
        Method     Coef. Std. Err.         z     P&gt;|z|      [ 95% C.I. ]       
=============================================================================
  Conventional   -12.013     1.394    -8.619     0.000   [-14.745 , -9.281]    
        Robust         -         -    -7.244     0.000   [-15.473 , -8.883]    
=============================================================================</code></pre>
</div>
</div>
<p>Make a plot of the effect using <code>rdplot()</code>. You’ll use the same <code>y</code>, <code>x</code>, and <code>c</code> that you did in <code>rdrobust()</code> above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rdplot</span>(<span class="at">y =</span> program<span class="sc">$</span>grade, <span class="at">x =</span> program<span class="sc">$</span>attendance, <span class="at">c =</span> <span class="dv">80</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TamaraMallory_problem-set-6_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="nonparametric-sensitivity-checks" class="level2">
<h2 class="anchored" data-anchor-id="nonparametric-sensitivity-checks">Nonparametric sensitivity checks</h2>
<p>Now that we have an effect, we can adjust some of the default options to see how robust the effect size is.</p>
<p>First we’ll play with the bandwidth. Find the ideal bandwidth with with <code>rdbwselect()</code>, then run <code>rdrobust</code> with twice that bandwidth and half that bandwidth (hint: use <code>h = SOMETHING</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the ideal bandwidth. Make sure rdbwselect() pipes into summary() so you</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># can see the results: rdbwselect() |&gt; summary()</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># You'll use the same y, x, and c as before</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rdbwselect</span>(<span class="at">y =</span> program<span class="sc">$</span>grade, <span class="at">x =</span> program<span class="sc">$</span>attendance,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">c =</span> <span class="dv">80</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: rdbwselect

Number of Obs.                 1200
BW type                       mserd
Kernel                   Triangular
VCE method                       NN

Number of Obs.                  681          519
Order est. (p)                    1            1
Order bias  (q)                   2            2
Unique Obs.                     627          451

=======================================================
                  BW est. (h)    BW bias (b)
            Left of c Right of c  Left of c Right of c
=======================================================
     mserd     8.112      8.112     12.449     12.449
=======================================================</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rdbwselect</span>(<span class="at">y =</span> program<span class="sc">$</span>grade, <span class="at">x =</span> program<span class="sc">$</span>attendance,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">c =</span> <span class="dv">80</span>, <span class="at">all =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: rdbwselect

Number of Obs.                 1200
BW type                         All
Kernel                   Triangular
VCE method                       NN

Number of Obs.                  681          519
Order est. (p)                    1            1
Order bias  (q)                   2            2
Unique Obs.                     627          451

=======================================================
                  BW est. (h)    BW bias (b)
            Left of c Right of c  Left of c Right of c
=======================================================
     mserd     8.112      8.112     12.449     12.449
    msetwo    11.921      7.160     19.516     11.541
    msesum     7.172      7.172     12.341     12.341
  msecomb1     7.172      7.172     12.341     12.341
  msecomb2     8.112      7.172     12.449     12.341
     cerrd     5.691      5.691     12.449     12.449
    certwo     8.363      5.023     19.516     11.541
    cersum     5.032      5.032     12.341     12.341
  cercomb1     5.032      5.032     12.341     12.341
  cercomb2     5.691      5.032     12.449     12.341
=======================================================</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rdrobust() with half bandwidth</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rdrobust</span>(<span class="at">y =</span> program<span class="sc">$</span>grade, <span class="at">x =</span> program<span class="sc">$</span>attendance,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">c =</span> <span class="dv">80</span>, <span class="at">h =</span> <span class="fl">8.112</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sharp RD estimates using local polynomial regression.

Number of Obs.                 1200
BW type                      Manual
Kernel                   Triangular
VCE method                       NN

Number of Obs.                  681          519
Eff. Number of Obs.             122          146
Order est. (p)                    1            1
Order bias  (q)                   2            2
BW est. (h)                   4.056        4.056
BW bias (b)                   4.056        4.056
rho (h/b)                     1.000        1.000
Unique Obs.                     681          519

=============================================================================
        Method     Coef. Std. Err.         z     P&gt;|z|      [ 95% C.I. ]       
=============================================================================
  Conventional   -12.761     2.000    -6.380     0.000   [-16.681 , -8.841]    
        Robust         -         -    -3.913     0.000   [-16.492 , -5.485]    
=============================================================================</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rdrobust() with two times the bandwidth</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rdrobust</span>(<span class="at">y =</span> program<span class="sc">$</span>grade, <span class="at">x =</span> program<span class="sc">$</span>attendance,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">c =</span> <span class="dv">80</span>, <span class="at">h =</span> <span class="fl">8.112</span> <span class="sc">*</span> <span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sharp RD estimates using local polynomial regression.

Number of Obs.                 1200
BW type                      Manual
Kernel                   Triangular
VCE method                       NN

Number of Obs.                  681          519
Eff. Number of Obs.             436          490
Order est. (p)                    1            1
Order bias  (q)                   2            2
BW est. (h)                  16.224       16.224
BW bias (b)                  16.224       16.224
rho (h/b)                     1.000        1.000
Unique Obs.                     681          519

=============================================================================
        Method     Coef. Std. Err.         z     P&gt;|z|      [ 95% C.I. ]       
=============================================================================
  Conventional   -11.327     0.980   -11.554     0.000   [-13.248 , -9.405]    
        Robust         -         -    -8.613     0.000   [-15.499 , -9.753]    
=============================================================================</code></pre>
</div>
</div>
<p>Next we’ll play with the kernel. Use the default ideal bandwidth and adjust the kernel to change how heavily weighted the observations right by the cutoff are. You already used a triangular kernel—that was the first <code>rdrobust()</code> model you ran, since triangular is the default. Try using Epanechnikov and uniform kernels (look at the help file for <code>rdrobust</code> or look at the in-class example to see how to specify different kernels):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rdrobust() with an Epanechnikov kernel</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rdrobust</span>(<span class="at">y =</span> program<span class="sc">$</span>grade, <span class="at">x =</span> program<span class="sc">$</span>attendance,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">c =</span> <span class="dv">80</span>, <span class="at">kernel =</span> <span class="st">"epanechnikov"</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sharp RD estimates using local polynomial regression.

Number of Obs.                 1200
BW type                       mserd
Kernel                   Epanechnikov
VCE method                       NN

Number of Obs.                  681          519
Eff. Number of Obs.             245          261
Order est. (p)                    1            1
Order bias  (q)                   2            2
BW est. (h)                   7.780        7.780
BW bias (b)                  12.498       12.498
rho (h/b)                     0.622        0.622
Unique Obs.                     627          451

=============================================================================
        Method     Coef. Std. Err.         z     P&gt;|z|      [ 95% C.I. ]       
=============================================================================
  Conventional   -11.910     1.377    -8.649     0.000   [-14.609 , -9.211]    
        Robust         -         -    -7.313     0.000   [-15.348 , -8.860]    
=============================================================================</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rdrobust() with a uniform kernel</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rdrobust</span>(<span class="at">y =</span> program<span class="sc">$</span>grade, <span class="at">x =</span> program<span class="sc">$</span>attendance,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">c =</span> <span class="dv">80</span>, <span class="at">kernel =</span> <span class="st">"uniform"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sharp RD estimates using local polynomial regression.

Number of Obs.                 1200
BW type                       mserd
Kernel                      Uniform
VCE method                       NN

Number of Obs.                  681          519
Eff. Number of Obs.             195          231
Order est. (p)                    1            1
Order bias  (q)                   2            2
BW est. (h)                   6.441        6.441
BW bias (b)                  11.081       11.081
rho (h/b)                     0.581        0.581
Unique Obs.                     627          451

=============================================================================
        Method     Coef. Std. Err.         z     P&gt;|z|      [ 95% C.I. ]       
=============================================================================
  Conventional   -11.531     1.448    -7.965     0.000   [-14.368 , -8.694]    
        Robust         -         -    -6.817     0.000   [-15.171 , -8.395]    
=============================================================================</code></pre>
</div>
</div>
</section>
</section>
<section id="step-6-compare-all-the-effects" class="level1">
<h1>Step 6: Compare all the effects</h1>
<p><strong>Make a list of all the effects you found. Which one do you trust the most? Why?</strong> I trust the nonparametric results with the bandwith of 8.457 because it looks at the individuals with attendance of 80% ± 10%. The data there can be more generalized than the others.</p>
<p>Write them in this table if it’s helpful: | Method | Bandwidth | Kernel | Estimate | | :———–: | :————-: | :———-: | :——: | | Parametric | Full data | Unweighted | 5.884 | | Parametric | 10 | Unweighted | 11.869 | | Parametric | 5 | Unweighted | 12.340 | | Nonparametric | 8.112 | Triangular | 12.013 | | Nonparametric | 4.056 (half) | Triangular | 12.761 | | Nonparametric | 16.224 (double) | Triangular | 11.327 | | Nonparametric | 7.780 | Epanechnikov | 11.910 | | Nonparametric | 6.441 | Uniform | 11.531 |</p>
<p><strong>Does the program have an effect? Should it be rolled out to all schools? Why or why not?</strong> The parametric results suggest that the program has a positive effect. The program has a cause of an increase of 12ish points in the final grade for those around the cutoff (the local average treatment effect, or LATE). The nonparametric estimate changes very little across different bandwidths and kernels. The program has a significant LATE but there is not enough evidence to decide whether the program should be rolled out to all schools. More evidence besides LATE goes into programs. Also, because this is the LATE, it’s only really valid for students in the bandwidth area. If a school has higher or lower average attendance, the causal evidence we have doesn’t apply to it.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>